# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8004677a635c8d9e30d65facd982c192e2d843b133d7d94296922abe732a6af762c762c03d3caf6ce48b1ac8180b1d33d36dfa0814e1b4ff2b3a3a3ca106cc0

test:
  secret_key_base: 3198deafcee5739ffbbeffcedeaaec3f490f881855df0cffb6fcf54823b9da92979ef8f9f10c2cf195fc37df5e4f9688efe3557ac72715ccad80ec6ca8b69181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
